version: "3.8"
services:
  app:
    build: 
      context: .
      dockerfile: ./infra/php/Dockerfile
    volumes:
      - ./backend:/work
      - ./logs:/var/log/php
      - ./infra/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /work
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=dbuser
      - DB_PASSWORD=dbpass
    command: >
      bash -c 'php artisan ui bootstrap --auth &&
      npm install && npm run dev &&
      php /usr/bin/composer dump-autoload &&
      php artisan migrate --force &&
      php artisan db:seed --force &&
      php-fpm'

  web:
    image: nginx:1.18-alpine
    ports:
      - 80:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Tokyo
      MYSQL_DATABASE: laravel
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      MYSQL_ROOT_PASSWORD: R00tPa55w0rd
