version: "3.8"
services:
  app:
    build: 
      context: ./infra/php
    volumes:
      - ./backend:/work
      - ./logs:/var/log/php
      - ./infra/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /work
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db

  web:
    image: nginx:1.18-alpine
    ports:
      - 80:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db-store:
